### ISSUE TITLE
Modul za registraciju korisnika

### ISSUE THREAD

**Issue by erminhadzic4** [erminhadzic4/NRS2023-Projekat#1]
Napraviti početni ekran aplikacije koji će sadržavati polja za unos sljedećih podataka:

- [x] email 
- [x] ime
- [x] prezime
- [x] adresu
- [x] broj telefona
- [x] ostalo (po potrebi, npr. dugme za prijavu pomoću Google accounta-a, Apple korisničkog računa i sl.) 
- [x] istestirati

**Developer koji prihvati issue pravi novi branch na kojem će raditi odvojeno od master branch-a.**

**Comment by afrljak1** [comment]
uraden code review, sve ok.
