### ISSUE TITLE
Sortiranje liste transakcija - testiranje

### ISSUE THREAD

**Issue by obukurevic1** [erminhadzic4/NRS2023-Projekat#54]

**Comment by sejmalemes** [comment]
Testiranje grupe 3 zavrseno

**Comment by eminakahvedzic** [comment]
Prilikom generisanja novih podataka, sortiranje se ne izvršava korektno.

**Comment by aatlic** [comment]
Prilikom generisanja podataka sortiranje se ne izvršava, tek kada se ponovo odabere opcija sortiranja tada se sortiranje vrši na generisanim podacima.
